#!/usr/bin/env bash

set -euo pipefail

readonly default_image="hashicorp/vault"
readonly default_tag="1.13.1"
readonly image="${BUILDKITE_PLUGIN_VAULT_SECRETS_IMAGE:-${default_image}}:${BUILDKITE_PLUGIN_VAULT_SECRETS_TAG:-${default_tag}}"
readonly container_name="vault-secrets-env-plugin-${BUILDKITE_JOB_ID}"

# Resolve Vault address
########################################################################
if [ -n "${BUILDKITE_PLUGIN_VAULT_SECRETS_ADDRESS:-}" ]; then
    VAULT_ADDR="${BUILDKITE_PLUGIN_VAULT_SECRETS_ADDRESS}"
    export VAULT_ADDR
fi
if [ -z "${VAULT_ADDR:-}" ]; then
    echo "--- :skull_and_crossbones: Could not find 'VAULT_ADDR' in the environment, and 'BUILDKITE_PLUGIN_VAULT_SECRETS_ADDRESS' was not specified!"
    exit 1
fi

# Fail if there is no Vault token; need to be able to auth with vault.
########################################################################
if [ -n "${BUILDKITE_PLUGIN_VAULT_SECRETS_TOKEN:-}" ]; then
    VAULT_TOKEN="${BUILDKITE_PLUGIN_VAULT_SECRETS_TOKEN}"
    export VAULT_TOKEN
fi

_source="${BASH_SOURCE[0]}"
[ -z "${_source:-}" ] && _source="${0}"
basedir="$( cd "$( dirname "${_source}" )" && cd .. && pwd )"

# shellcheck disable=SC1090
. "$basedir/lib/shared.sh"

if [ -z "${VAULT_TOKEN:-}" ]; then
  if [ -n "${BUILDKITE_PLUGIN_VAULT_SECRETS_AUTH_METHOD:-"aws"}" ]; then
    vault_login_with_${BUILDKITE_PLUGIN_VAULT_SECRETS_AUTH_METHOD:-"aws"}_auth
  fi
  if [ -z "${VAULT_TOKEN:-}" ]; then
    echo "--- :skull_and_crossbones: Could not find 'VAULT_TOKEN' in the environment!"
    exit 1
  fi
fi

trap cleanup EXIT INT QUIT

# read secrets and set them into individual environment variables
secret_path="$(strip_quotes ${BUILDKITE_PLUGIN_VAULT_SECRETS_PATH})"
load_secrets_into_env "${secret_path}"
